<?php

use Sunrise\Http\Router\OpenApi\Controller\SwaggerController;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <?php foreach (${SwaggerController::CSS_URLS_VAR_NAME} as $url): ?>
        <link href="<?= $url ?>" rel="stylesheet">
    <?php endforeach ?>
</head>
<body>
<div id="app"></div>
<?php foreach (${SwaggerController::JS_URLS_VAR_NAME} as $url): ?>
    <script src="<?= $url ?>"></script>
<?php endforeach ?>
<script>
    window.onload = function() {
        window.ui = SwaggerUIBundle({
            url: '<?= ${SwaggerController::OPENAPI_URI_VAR_NAME} ?>',
            dom_id: '#app',
            presets: [
                SwaggerUIBundle.presets.apis,
            ],
        });
    };
</script>
</body>
</html>
