<?php

use Sunrise\Http\Router\OpenApi\Controller\SwaggerUiController;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.18.2/swagger-ui.min.css" rel="stylesheet">
</head>
<body>
<div id="swagger-ui"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.18.2/swagger-ui-bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.18.2/swagger-ui-standalone-preset.min.js"></script>
<script>
    window.onload = function() {
        window.ui = SwaggerUIBundle({
            url: '<?= ${SwaggerUiController::OPENAPI_URI_TEMPLATE_VAR_NAME} ?>',
            dom_id: '#swagger-ui',
            presets: [
                SwaggerUIBundle.presets.apis,
            ],
        });
    };
</script>
</body>
</html>
